- name: variable
  hosts: local
  connection: local
  vars: 
   COURSE: ANSIBLE
   DURATION: 7DAYS
  tasks: 
   - name: vars printing 
     ansible.builtin.debug:
      msg: "${{COURSE}} , ${{DURATION}}"