- name: vars from args
  hosts: local
  connection: local
  tasks:
  - name: vars from args
    ansible.builtin.debug:
     msg: "{{duration}}----{{trainer}}----{{course}}"

#  ansible-playbook -i inventory.ini -e ansible_user=ec2-user
#                                    -e ansible_password=DevOps321
#                                    -e "trainer=siv" -e "duration=1hr"
#                                    -e "course=dev" 08-varsfromargs.yaml

