- name: installing nginx server based on os
  hosts: local
  connection: local
  tasks: 
   - name: installing inginx if redhat
     ansible.builtin.dnf:
       name: nginx
       state: latest
     when: ansible_os_family=="RedHat" #use ansible while referring the facts

   - name: installing nginx for ubuntu
     ansible.builtin.apt:
       name: nginx
       state: latest
     when: ansible_os_family=="Debain"