- name: installing packages
  hosts: local
  connection: local
  become: yes
  tasks:
   - name: installin nginx mysql zip
     ansible.builtin.package:
      name: "{{ item }}"
      state: latest
     loop:
     - nginx
     - mysql
     - zip
    
