- name: functions in ansible
  hosts: local
  connection: local
  vars:
    technologies: DevOps, Linux, Shell, Ansible # string
  # dictionary == map
  tags:
    Application: payment
    Environment: dev
  tasks:
   - name: defult value for var
     ansible.builtin.debug:
      msg: "default value: {{name | default('rakesh')}}"
     # string to list
   - name: splitting strings
     ansible.builtin.debug:
      msg: " techs are {{technologies | split( ',' )}}"
   - name: dir to map
     ansible.builtin.debug:
      msg: " techs are {{tags | dict2items}}"
      