- name: error handling 
  hosts: local
  connection: local
  tasks:
   - name: check for user
     ansible.builtin.command: id roboshop
     register: user_output
     ignore_errors: true
   - name: print output
     ansible.builtin.debug:
      msg: "{{user_output.rc}}"
   - name: user creation
     ansible.builtin.command: useradd roboshop
     when: user_output.rc != 0
    